/**
 * SVG Export Utilities
 * 
 * Provides SVG export functionality for CAD compatibility
 * SVG is vector-based and maintains precision for technical drawings
 */

import { Stage } from 'konva/lib/Stage';
import { ViewType2D } from '@/types/views';
import { Element2D } from '@/types/elements2D';

export interface SVGExportOptions {
  width: number;
  height: number;
  scale: number;
  includeGrid: boolean;
  includeMeasurements: boolean;
  includeAnnotations: boolean;
  precision: number; // Decimal places for coordinates
  units: 'mm' | 'cm' | 'in' | 'ft';
  strokeWidth: number;
  fontSize: number;
  title?: string;
  description?: string;
}

export const DEFAULT_SVG_OPTIONS: SVGExportOptions = {
  width: 800,
  height: 600,
  scale: 1,
  includeGrid: false,
  includeMeasurements: true,
  includeAnnotations: true,
  precision: 2,
  units: 'mm',
  strokeWidth: 1,
  fontSize: 12,
  title: 'House Plan',
  description: 'Generated by 2D House Planner'
};

/**
 * Generate filename for SVG export
 */
export function generateSVGFilename(title: string = 'house-plan'): string {
  const timestamp = new Date().toISOString().slice(0, 19).replace(/[:.]/g, '-');
  const sanitizedTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '-');
  return sanitizedTitle + '-' + timestamp + '.svg';
}
